version: '2'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: "python manage.py celery  worker -l info"
    environment:
      - DATABASE_URL=mysql://root:@172.20.10.2/integra_backend
    links:
      - redis
    volumes:
      - .:/code
    depends_on:
      - redis
  
  web:
    restart: always
    image: web
    build: ./
    volumes:
      - ./:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - DATABASE_URL=mysql://root:@172.30.16.124/integra_backend

volumes:
  static_volume:
  media_volume: