version: '2'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 80:80
    depends_on:
      - web

  web:
    restart: always
    image: web
    build: ./
    volumes:
      - ./:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - DATABASE_URL=mysql://root:@172.30.16.124/integra_backend

volumes:
  static_volume: