site_name: integrabackend
site_description: Description
repo_url: https://github.com/erasmo07/integra_backend
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/erasmo07">erasmo07</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
